-- AlterTable: eventos sem paciente (ex.: login da equipe)
ALTER TABLE "AuditEvent" ALTER COLUMN "clientId" DROP NOT NULL;

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'STAFF_LOGIN_SUCCESS';
ALTER TYPE "AuditEventType" ADD VALUE 'STAFF_LOGIN_FAILED';
ALTER TYPE "AuditEventType" ADD VALUE 'STAFF_PASSWORD_CHANGED';
ALTER TYPE "AuditEventType" ADD VALUE 'STAFF_PASSWORD_RESET';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_PORTAL_SESSION_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_PORTAL_LINK_GENERATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_DELETED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_PATHWAY_STARTED';
ALTER TYPE "AuditEventType" ADD VALUE 'PATIENT_PATHWAY_COMPLETED';
ALTER TYPE "AuditEventType" ADD VALUE 'FILE_DOWNLOADED_BY_STAFF';
ALTER TYPE "AuditEventType" ADD VALUE 'FILE_DOWNLOADED_BY_PATIENT';
ALTER TYPE "AuditEventType" ADD VALUE 'CHECKLIST_ITEM_TOGGLED';
ALTER TYPE "AuditEventType" ADD VALUE 'FILE_DELETED';
