import type { LibraryFileSeed, TenantSeed } from "./types";

const BASE_LIBRARY_FILES: LibraryFileSeed[] = [
  {
    alias: "pedido-tomografia",
    fileName: "pedido-tomografia.pdf",
    mimeType: "application/pdf",
    sizeBytes: 248_120,
  },
  {
    alias: "checklist-preop",
    fileName: "checklist-pre-operatorio.pdf",
    mimeType: "application/pdf",
    sizeBytes: 181_704,
  },
  {
    alias: "termo-consentimento",
    fileName: "termo-consentimento.pdf",
    mimeType: "application/pdf",
    sizeBytes: 322_412,
  },
  {
    alias: "orientacoes-posop",
    fileName: "orientacoes-pos-operatorias.pdf",
    mimeType: "application/pdf",
    sizeBytes: 205_890,
  },
  {
    alias: "guia-internacao",
    fileName: "guia-internacao.pdf",
    mimeType: "application/pdf",
    sizeBytes: 219_640,
  },
  {
    alias: "risco-cirurgico",
    fileName: "avaliacao-risco-cirurgico.pdf",
    mimeType: "application/pdf",
    sizeBytes: 168_240,
  },
];

export const tenants: TenantSeed[] = [
  {
    slug: "clinica-alpha",
    name: "Clínica Alpha",
    taxId: "12.345.678/0001-90",
    phone: "(11) 4002-1000",
    addressLine: "Av. Paulista, 1200, cj. 1102",
    city: "São Paulo",
    postalCode: "01310-100",
    affiliatedHospitals: "Hospital Sírio-Libanês\nHospital Samaritano Paulista\nHospital Oswaldo Cruz",
    notifications: {
      notifyCriticalAlerts: true,
      notifySurgeryReminders: true,
      notifyNewPatients: true,
      notifyWeeklyReport: true,
      notifyDocumentDelivery: true,
    },
    adminEmail: "admin-alpha@bucomax.local",
    adminName: "Dra. Helena Almeida",
    userEmail: "user-alpha@bucomax.local",
    userName: "Enf. Bruno Lopes",
    suppliers: [
      { name: "Art Fix", active: true },
      { name: "NeoGuide", active: true },
      { name: "BioImplant", active: false },
    ],
    libraryFiles: BASE_LIBRARY_FILES,
    pathways: [
      {
        key: "ortognatica",
        name: "Cirurgia ortognática",
        description: "Fluxo principal de avaliação, autorização, cirurgia e retorno do paciente.",
        publishedStages: [
          {
            key: "avaliacao-inicial",
            name: "Avaliação inicial",
            patientMessage: "Bem-vindo. Nesta etapa coletamos documentação e definimos os próximos exames.",
            alertWarningDays: 2,
            alertCriticalDays: 4,
            checklist: ["Confirmar cadastro completo", "Anexar exames iniciais"],
            documentAliases: ["pedido-tomografia", "checklist-preop"],
          },
          {
            key: "exames-pre-operatorios",
            name: "Exames pré-operatórios",
            patientMessage: "Reforce a necessidade de tomografia e avaliação de risco cirúrgico.",
            alertWarningDays: 5,
            alertCriticalDays: 8,
            checklist: ["Receber tomografia", "Validar risco cirúrgico"],
            documentAliases: ["pedido-tomografia", "risco-cirurgico"],
          },
          {
            key: "autorizacao-hospitalar",
            name: "Autorização hospitalar",
            patientMessage: "Confirmar convênio, hospital e documentação obrigatória.",
            alertWarningDays: 4,
            alertCriticalDays: 6,
            checklist: ["Autorizar convênio", "Confirmar hospital"],
            documentAliases: ["termo-consentimento", "guia-internacao"],
          },
          {
            key: "cirurgia",
            name: "Cirurgia",
            patientMessage: "Paciente em programação cirúrgica.",
            alertWarningDays: 1,
            alertCriticalDays: 2,
            checklist: ["Checklist de centro cirúrgico", "Confirmar equipe"],
            documentAliases: ["termo-consentimento", "orientacoes-posop"],
          },
          {
            key: "pos-operatorio",
            name: "Pós-operatório",
            patientMessage: "Acompanhar retorno, prescrição e dúvidas do paciente.",
            alertWarningDays: 7,
            alertCriticalDays: 10,
            checklist: ["Agendar retorno", "Prescrição entregue"],
            documentAliases: ["orientacoes-posop"],
          },
        ],
        draftStages: [
          {
            key: "avaliacao-inicial",
            name: "Avaliação inicial",
            patientMessage: "Versão rascunho com etapa extra de planejamento.",
            alertWarningDays: 2,
            alertCriticalDays: 4,
            checklist: ["Confirmar cadastro completo", "Anexar exames iniciais"],
            documentAliases: ["pedido-tomografia", "checklist-preop"],
          },
          {
            key: "exames-pre-operatorios",
            name: "Exames pré-operatórios",
            patientMessage: "Receber exames atualizados antes do planejamento 3D.",
            alertWarningDays: 5,
            alertCriticalDays: 8,
            checklist: ["Receber tomografia", "Validar risco cirúrgico"],
            documentAliases: ["pedido-tomografia", "risco-cirurgico"],
          },
          {
            key: "planejamento-3d",
            name: "Planejamento 3D",
            patientMessage: "Conferência virtual do plano cirúrgico antes da autorização.",
            alertWarningDays: 3,
            alertCriticalDays: 5,
            checklist: ["Aprovar setup virtual"],
            documentAliases: ["guia-internacao"],
          },
          {
            key: "autorizacao-hospitalar",
            name: "Autorização hospitalar",
            patientMessage: "Confirmar convênio, hospital e documentação obrigatória.",
            alertWarningDays: 4,
            alertCriticalDays: 6,
            checklist: ["Autorizar convênio", "Confirmar hospital"],
            documentAliases: ["termo-consentimento", "guia-internacao"],
          },
          {
            key: "cirurgia",
            name: "Cirurgia",
            patientMessage: "Paciente em programação cirúrgica.",
            alertWarningDays: 1,
            alertCriticalDays: 2,
            checklist: ["Checklist de centro cirúrgico", "Confirmar equipe"],
            documentAliases: ["termo-consentimento", "orientacoes-posop"],
          },
          {
            key: "pos-operatorio",
            name: "Pós-operatório",
            patientMessage: "Acompanhar retorno, prescrição e dúvidas do paciente.",
            alertWarningDays: 7,
            alertCriticalDays: 10,
            checklist: ["Agendar retorno", "Prescrição entregue"],
            documentAliases: ["orientacoes-posop"],
          },
        ],
      },
      {
        key: "implante-zigomatico",
        name: "Implante zigomático",
        description: "Fluxo enxuto para casos de implante e reabilitação.",
        publishedStages: [
          {
            key: "triagem",
            name: "Triagem",
            patientMessage: "Coletar exames iniciais e preparar avaliação do caso.",
            alertWarningDays: 3,
            alertCriticalDays: 5,
            checklist: ["Triagem validada", "Exames solicitados"],
            documentAliases: ["pedido-tomografia"],
          },
          {
            key: "planejamento",
            name: "Planejamento",
            patientMessage: "Organizar planejamento e materiais do procedimento.",
            alertWarningDays: 4,
            alertCriticalDays: 6,
            checklist: ["Planejamento aprovado", "Materiais confirmados"],
            documentAliases: ["checklist-preop", "risco-cirurgico"],
          },
          {
            key: "procedimento",
            name: "Procedimento",
            patientMessage: "Paciente em janela de procedimento.",
            alertWarningDays: 1,
            alertCriticalDays: 2,
            checklist: ["Sala confirmada", "Equipe confirmada"],
            documentAliases: ["termo-consentimento"],
          },
          {
            key: "reabilitacao",
            name: "Reabilitação",
            patientMessage: "Acompanhamento pós-procedimento e retorno.",
            alertWarningDays: 6,
            alertCriticalDays: 9,
            checklist: ["Retorno agendado", "Orientações entregues"],
            documentAliases: ["orientacoes-posop"],
          },
        ],
      },
    ],
    clients: [
      {
        key: "ana-martins",
        name: "Ana Martins",
        phone: "(11) 99999-1001",
        email: "ana.martins@example.com",
        documentId: "123.456.789-00",
        caseDescription: "Paciente com assimetria facial e indicacao de cirurgia ortognatica.",
        createdDaysAgo: 4,
        assignedTo: "admin",
        supplierName: "Art Fix",
        pathwayKey: "ortognatica",
        currentStageKey: "avaliacao-inicial",
        enteredStageDaysAgo: 1,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 2,
      },
      {
        key: "bruno-costa",
        name: "Bruno Costa",
        phone: "(11) 99999-1002",
        email: "bruno.costa@example.com",
        documentId: "123.456.789-01",
        caseDescription: "Caso classe III com exames pré-operatórios em andamento.",
        createdDaysAgo: 18,
        assignedTo: "user",
        supplierName: "NeoGuide",
        pathwayKey: "ortognatica",
        currentStageKey: "exames-pre-operatorios",
        enteredStageDaysAgo: 6,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 2,
      },
      {
        key: "carla-souza",
        name: "Carla Souza",
        phone: "(11) 99999-1003",
        email: "carla.souza@example.com",
        documentId: "123.456.789-02",
        caseDescription: "Convênio demorando para liberar autorização hospitalar.",
        createdDaysAgo: 28,
        assignedTo: "admin",
        supplierName: "Art Fix",
        pathwayKey: "ortognatica",
        currentStageKey: "autorizacao-hospitalar",
        enteredStageDaysAgo: 9,
        completedChecklistCount: 0,
        noteCount: 3,
        clientFileCount: 1,
      },
      {
        key: "diego-lima",
        name: "Diego Lima",
        phone: "(11) 99999-1004",
        email: "diego.lima@example.com",
        documentId: "123.456.789-03",
        caseDescription: "Paciente confirmado para cirurgia esta semana.",
        createdDaysAgo: 15,
        assignedTo: "user",
        supplierName: "NeoGuide",
        pathwayKey: "ortognatica",
        currentStageKey: "cirurgia",
        enteredStageDaysAgo: 1,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 2,
      },
      {
        key: "elisa-rocha",
        name: "Elisa Rocha",
        phone: "(11) 99999-1005",
        email: "elisa.rocha@example.com",
        documentId: "123.456.789-04",
        caseDescription: "Pós-operatório com retorno e revisão de prescrição.",
        createdDaysAgo: 36,
        assignedTo: "admin",
        supplierName: "Art Fix",
        pathwayKey: "ortognatica",
        currentStageKey: "pos-operatorio",
        enteredStageDaysAgo: 4,
        completedChecklistCount: 2,
        noteCount: 3,
        clientFileCount: 2,
      },
      {
        key: "fernanda-alves",
        name: "Fernanda Alves",
        phone: "(11) 99999-1006",
        email: "fernanda.alves@example.com",
        documentId: "123.456.789-05",
        caseDescription: "Lead recém-cadastrado aguardando definição da jornada ideal.",
        createdDaysAgo: 2,
        assignedTo: "user",
        supplierName: null,
        noteCount: 1,
        clientFileCount: 1,
      },
      {
        key: "gabriel-oliveira",
        name: "Gabriel Oliveira",
        phone: "(11) 99999-1007",
        email: "gabriel.oliveira@example.com",
        documentId: "123.456.789-06",
        caseDescription: "Caso de implante zigomático já em fase de planejamento.",
        createdDaysAgo: 12,
        assignedTo: "admin",
        supplierName: "NeoGuide",
        pathwayKey: "implante-zigomatico",
        currentStageKey: "planejamento",
        enteredStageDaysAgo: 5,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 2,
      },
    ],
  },
  {
    slug: "clinica-beta",
    name: "Clínica Beta",
    taxId: "98.765.432/0001-11",
    phone: "(21) 3000-2200",
    addressLine: "Rua Voluntários da Pátria, 410, sala 604",
    city: "Rio de Janeiro",
    postalCode: "22270-000",
    affiliatedHospitals: "Hospital Copa Star\nCasa de Saúde São José",
    notifications: {
      notifyCriticalAlerts: true,
      notifySurgeryReminders: false,
      notifyNewPatients: true,
      notifyWeeklyReport: false,
      notifyDocumentDelivery: true,
    },
    adminEmail: "admin-beta@bucomax.local",
    adminName: "Dr. Rafael Campos",
    userEmail: "user-beta@bucomax.local",
    userName: "Coord. Julia Ribeiro",
    suppliers: [
      { name: "Evolve", active: true },
      { name: "MaxFace", active: true },
      { name: "Oral Prime", active: false },
    ],
    libraryFiles: BASE_LIBRARY_FILES,
    pathways: [
      {
        key: "trauma-facial",
        name: "Trauma Facial",
        description: "Acompanhamento de trauma com exames, cirurgia e retorno.",
        publishedStages: [
          {
            key: "triagem",
            name: "Triagem",
            patientMessage: "Registrar caso e abrir os exames iniciais.",
            alertWarningDays: 2,
            alertCriticalDays: 4,
            checklist: ["Cadastro validado", "Exames solicitados"],
            documentAliases: ["pedido-tomografia"],
          },
          {
            key: "preparo-cirurgico",
            name: "Preparo cirúrgico",
            patientMessage: "Fechar preparo do paciente antes da cirurgia.",
            alertWarningDays: 4,
            alertCriticalDays: 6,
            checklist: ["Risco cirúrgico validado", "Hospital confirmado"],
            documentAliases: ["risco-cirurgico", "guia-internacao"],
          },
          {
            key: "cirurgia",
            name: "Cirurgia",
            patientMessage: "Paciente em programação de cirurgia.",
            alertWarningDays: 1,
            alertCriticalDays: 2,
            checklist: ["Equipe alinhada", "Checklist concluído"],
            documentAliases: ["termo-consentimento"],
          },
          {
            key: "retorno",
            name: "Retorno",
            patientMessage: "Monitorar evolução e próximos retornos.",
            alertWarningDays: 5,
            alertCriticalDays: 8,
            checklist: ["Retorno confirmado", "Orientações reforçadas"],
            documentAliases: ["orientacoes-posop"],
          },
        ],
      },
    ],
    clients: [
      {
        key: "helena-porto",
        name: "Helena Porto",
        phone: "(21) 98888-2001",
        email: "helena.porto@example.com",
        documentId: "987.654.321-00",
        caseDescription: "Paciente em triagem após trauma facial leve.",
        createdDaysAgo: 3,
        assignedTo: "admin",
        supplierName: "Evolve",
        pathwayKey: "trauma-facial",
        currentStageKey: "triagem",
        enteredStageDaysAgo: 1,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 1,
      },
      {
        key: "igor-melo",
        name: "Igor Melo",
        phone: "(21) 98888-2002",
        email: "igor.melo@example.com",
        documentId: "987.654.321-01",
        caseDescription: "Caso com preparo cirúrgico avançado e documentos completos.",
        createdDaysAgo: 17,
        assignedTo: "user",
        supplierName: "MaxFace",
        pathwayKey: "trauma-facial",
        currentStageKey: "preparo-cirurgico",
        enteredStageDaysAgo: 5,
        completedChecklistCount: 1,
        noteCount: 2,
        clientFileCount: 2,
      },
      {
        key: "julia-nunes",
        name: "Julia Nunes",
        phone: "(21) 98888-2003",
        email: "julia.nunes@example.com",
        documentId: "987.654.321-02",
        caseDescription: "Retorno atrasado no pós-operatório, precisa de contato do time.",
        createdDaysAgo: 24,
        assignedTo: "admin",
        supplierName: "Evolve",
        pathwayKey: "trauma-facial",
        currentStageKey: "retorno",
        enteredStageDaysAgo: 9,
        completedChecklistCount: 0,
        noteCount: 3,
        clientFileCount: 2,
      },
      {
        key: "karen-silva",
        name: "Karen Silva",
        phone: "(21) 98888-2004",
        email: "karen.silva@example.com",
        documentId: "987.654.321-03",
        caseDescription: "Paciente aguardando definição se entrará em jornada ou ficará só em acompanhamento.",
        createdDaysAgo: 1,
        assignedTo: "user",
        supplierName: null,
        noteCount: 1,
        clientFileCount: 1,
      },
    ],
  },
];
